# Generated by Django 2.2.1 on 2019-05-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimo'},
        ),
    ]
