# Generated by Django 2.2.1 on 2019-05-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='client_id',
            field=models.ForeignKey(default=None, help_text='unique id of a client.', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='amount of the payment made or missed in dollars.', max_digits=12),
        ),
    ]
