# Generated by Django 2.2.1 on 2019-05-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0002_auto_20190513_2035'),
        ('loan_app', '0002_auto_20190517_1710'),
    ]

    operations = [
    ]
